### ISSUE TITLE
Any example of payment API ?

### ISSUE THREAD

**Issue by qasimzee** [turingou/wechat#2]
I am unable to find how to use payment API so far. Any help ?

**Comment by guo-yu** [comment]
This module did not wrap Wechat pay API, check out Wechat JS SDK (by Tencent) instead: http://mp.weixin.qq.com/wiki/7/aaa137b55fb2e0456bf8dd9148dd613f.html

FYI, example here:http://demo.open.weixin.qq.com/jssdk/
